/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CPqrIcfDicx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function SignPage() {
  return (
    <div className="flex flex-col min-h-screen bg-[#0B2545] text-white">
      <header className="flex items-center justify-between px-4 py-3 sm:px-6 lg:px-8">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <CompassIcon className="h-6 w-6 text-primary" />
          <span className="text-lg font-semibold">Disaster Prep</span>
        </Link>
      </header>
      <main className="flex-1 flex items-center justify-center py-12 sm:py-16 lg:py-20">
        <div className="w-full max-w-md space-y-8 px-4 sm:px-6 lg:px-8">
          <div>
            <h2 className="mt-6 text-center text-3xl font-bold tracking-tight">Join the Community</h2>
            <p className="mt-2 text-center text-sm text-[#94A3B8]">
              Create your account to stay informed and get involved.
            </p>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <Button
              variant="outline"
              className="flex items-center justify-center gap-2 border-[#94A3B8] text-white hover:bg-[#FF6B6B] hover:text-[#0B2545]"
            >
              <GithubIcon className="h-5 w-5 animate-bounce " />
              Github
            </Button>
            <Button
              variant="outline"
              className="flex items-center justify-center gap-2 border-[#94A3B8] text-white hover:bg-[#FF6B6B] hover:text-[#0B2545]"
            >
              <MailIcon className="h-5 w-5 animate-bounce" />
              Google
            </Button>
          </div>
          <div className="relative">
            <div className="absolute inset-0 flex items-center">
              <span className="w-full border-t border-[#94A3B8]" />
            </div>
            <div className="relative flex justify-center text-sm">
              <span className="bg-[#0B2545] px-2 text-[#94A3B8]">Or continue with</span>
            </div>
          </div>
          <form className="space-y-6">
            <div>
              <Label htmlFor="email" className="block text-sm font-medium">
                Email
              </Label>
              <div className="mt-1">
                <Input
                  id="email"
                  type="email"
                  className="block w-full appearance-none rounded-md border border-[#94A3B8] bg-[#0B2545] px-3 py-2 text-white placeholder-[#94A3B8] focus:border-[#4F46E5] focus:outline-none focus:ring-[#4F46E5]"
                />
              </div>
            </div>
            <div>
              <Label htmlFor="password" className="block text-sm font-medium">
                Password
              </Label>
              <div className="mt-1">
                <Input
                  id="password"
                  type="password"
                  className="block w-full appearance-none rounded-md border border-[#94A3B8] bg-[#0B2545] px-3 py-2 text-white placeholder-[#94A3B8] focus:border-[#4F46E5] focus:outline-none focus:ring-[#4F46E5]"
                />
              </div>
            </div>
            <div>
              <Button
                variant="outline"
                className="flex w-full items-center justify-center gap-2 border-[#94A3B8] text-white hover:bg-[#FF6B6B] hover:text-[#0B2545] transition-all duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-[#FF6B6B] focus:ring-offset-2"
              >
                Sign Up
              </Button>
            </div>
            <div>
              <Button
                variant="outline"
                className="flex w-full items-center justify-center gap-2 border-[#94A3B8] text-white hover:bg-[#FF6B6B] hover:text-[#0B2545] transition-all duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-[#FF6B6B] focus:ring-offset-2"
              >
                Sign In
              </Button>
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}

function GithubIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function MailIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}

function CompassIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" />
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}